openapi: 3.1.0
info:
  version: 1.0.0
  title: Products App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: 'This is my products app'
tags:
  - name: Products
    description: Operations about products.
  # теги, що ви будете використовувати
servers:
  - url: http://localhost:3000
  # - url: #посилання на задеплоєний сайт
paths:
  /products:
    get:
      $ref: ../swagger/paths/products/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
